library package PublicDescriptiveElements{
    public import DescriptiveModelLibrary::DescriptiveStateMachine;
    public import DescriptiveModelLibrary::QueryHistory;
    public import DescriptiveModelLibrary::DescriptiveState;
    public import DescriptiveModelLibrary::DescriptiveStrategy;
    public import DescriptiveModelLibrary::GroupedHistoryQuery;
    public import DescriptiveModelLibrary::QueryResult;

    
}